@node Download
@unnumbered Download

Preferable way is to download tarball with the signature from
website and, for example, run tests with benchmarks:

@verbatim
$ wget http://gogost.cypherpunks.ru/gogost-4.1.0.tar.xz
$ wget http://gogost.cypherpunks.ru/gogost-4.1.0.tar.xz.sig
$ gpg --verify gogost-4.1.0.tar.xz.sig gogost-4.1.0.tar.xz
$ xz -d < gogost-4.1.0.tar.xz | tar xf -
$ make -C gogost-4.1.0 all bench
$ echo hello world | ./gogost-4.1.0/streebog256
f72018189a5cfb803dbe1f2149cf554c40093d8e7f81c21e08ac5bcd09d9934d
@end verbatim

And then you can include its source code in your project for example
like this:

@verbatim
$ mkdir -p myproj/src
$ cp -r gogost-4.1.0/src/go.cypherpunks.ru myproj/src
$ export GOPATH=$PWD/myproj
$ cd myproj/src
$ cat > main.go <<EOF
package main

import (
    "encoding/hex"
    "fmt"

    "go.cypherpunks.ru/gogost/v4/gost34112012256"
)

func main() {
    h := gost34112012256.New()
    h.Write([]byte("hello world\n"))
    fmt.Println(hex.EncodeToString(h.Sum(nil)))
}
EOF
$ go run main.go
f72018189a5cfb803dbe1f2149cf554c40093d8e7f81c21e08ac5bcd09d9934d
@end verbatim

@multitable {XXXXX} {XXXX-XX-XX} {XXXX KiB} {link sign} {xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} {xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
@headitem Version @tab Date @tab Size @tab Tarball @tab SHA256 checksum @tab Streebog-256 checksum

@item @ref{Release 4.1.0, 4.1.0} @tab 2019-10-03 @tab 55 KiB
@tab @url{gogost-4.1.0.tar.xz, link} @url{gogost-4.1.0.tar.xz.sig, sign}
@tab @code{F2FEF2E0 ADEB5742 FA2B3338 64E8B91B 3CCAA97D 5BA62177 21E08A11 F1FA8133}
@tab @code{72e0d52aa25158ab1bb45e5498ce703b516c616b71101b74d5ee259f516c4e91}

@item @ref{Release 4.0, 4.0} @tab 2019-08-12 @tab 56 KiB
@tab @url{gogost-4.0.tar.xz, link} @url{gogost-4.0.tar.xz.sig, sign}
@tab @code{4899B930 2110C9A9 592821D6 B206146F 2A66FC5A 3DEE9D6E 11F5EA51 72FEE6E6}
@tab @code{ad8b58d42c3829e66dd1994265478eab921393cf0f7a8b520d900e38092a2cd6}

@item @ref{Release 3.0, 3.0} @tab 2019-07-19 @tab 47 KiB
@tab @url{gogost-3.0.tar.xz, link} @url{gogost-3.0.tar.xz.sig, sign}
@tab @code{0BC2F39C DDB66493 BDF02DA7 C0A04633 E2A33462 4E3C0C7C 567712A6 6078FC82}
@tab @code{40de433a7e37fdca1ac2a9ef6093c85314937d59fa72e8e4dc91d5bf4eb064d7}

@item @ref{Release 2.0, 2.0} @tab 2016-11-26 @tab 39 KiB
@tab @url{gogost-2.0.tar.xz, link} @url{gogost-2.0.tar.xz.sig, sign}
@tab @code{28E8C15C 0EC5CC2A 47A8CCDA DF9EADB5 E46970AA FB7FAAF3 AA250FFC 79CE57F7}
@tab @code{e2858b9c1e7834663838c44b9b9ebbd1f37e5b85ceba5698b6fb5d180e071710}

@item 1.2 @tab 2016-11-13 @tab 34 KiB
@tab @url{gogost-1.2.tar.xz, link} @url{gogost-1.2.tar.xz.sig, sign}
@tab @code{B894D0E4 923F0361 8A33A360 65AE860F FCFAF8F5 42A82D71 EA0A0BA7 7BC99093}
@tab @code{fc6d3533e28d356398877674b6ee18954581c7f46832a5cf994ae243ab00ddf5}

@item @ref{Release 1.1, 1.1} @tab 2016-10-04 @tab 33 KiB
@tab @url{gogost-1.1.tar.xz, link} @url{gogost-1.1.tar.xz.sig, sign}
@tab @code{26D37912 6FE220C1 C0381835 DEFFDC4B BDCDC394 15D6E9C1 F8A5A302 04F9452B}
@tab @code{313fa58c2c030dd5acd20b524842bd2d4ec7403fcfca2a4a238ddc187c3ef0df}

@end multitable

You @strong{have to} verify downloaded tarballs integrity and
authenticity to be sure that you retrieved trusted and untampered
software. @url{https://www.gnupg.org/, The GNU Privacy Guard} is used
for that purpose.

For the very first time it is necessary to get signing public key and
import it. It is provided below, but you should check alternative
resources.

@verbatim
pub   rsa2048/0x82343436696FC85A 2016-09-13 [SC]
      CEBD 1282 2C46 9C02 A81A  0467 8234 3436 696F C85A
uid   GoGOST releases <gogost at cypherpunks dot ru>
@end verbatim

@itemize

@item @url{https://lists.cypherpunks.ru/mailman/listinfo/gost, gost} maillist

@item
@verbatim
$ gpg --auto-key-locate dane --locate-keys gogost at cypherpunks dot ru
$ gpg --auto-key-locate wkd --locate-keys gogost at cypherpunks dot ru
@end verbatim

@item
@verbatiminclude PUBKEY.asc

@end itemize

GoGOST is also @command{go get}-able. For example to use
@command{streebog256} utility:
@verbatim
$ go get go.cypherpunks.ru/gogost/cmd/streebog256
@end verbatim

@code{go.cypherpunks.ru} uses @url{https://www.cacert.org/, CACert.org}
certificate authority, that is not included by default in some operating
system distributions and probably you have to install it in your system,
because @command{go get} uses HTTPS connections. If you have issues
using either @code{sum.golang.org} or @code{proxy.golang.org}, then you
can disable their usage with @env{GOPRIVATE=go.cypherpunks.ru/gogost}
environment variable.

Also you can use @code{replace} feature inside your @file{go.mod}, like:
@verbatim
require go.cypherpunks.ru/gogost/v4 v4.1.0
replace go.cypherpunks.ru/gogost/v4 => /home/stargrave/gogost-4.1.0/src/go.cypherpunks.ru/gogost/v4
@end verbatim

You can obtain development source code with
@command{git clone git://git.cypherpunks.ru/gogost.git}.
